// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: imageConvolution.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_imageConvolution_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_imageConvolution_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_imageConvolution_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_imageConvolution_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_imageConvolution_2eproto;
namespace imageconv {
class ConvolutionResult;
struct ConvolutionResultDefaultTypeInternal;
extern ConvolutionResultDefaultTypeInternal _ConvolutionResult_default_instance_;
class ImageChunk;
struct ImageChunkDefaultTypeInternal;
extern ImageChunkDefaultTypeInternal _ImageChunk_default_instance_;
}  // namespace imageconv
PROTOBUF_NAMESPACE_OPEN
template<> ::imageconv::ConvolutionResult* Arena::CreateMaybeMessage<::imageconv::ConvolutionResult>(Arena*);
template<> ::imageconv::ImageChunk* Arena::CreateMaybeMessage<::imageconv::ImageChunk>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace imageconv {

// ===================================================================

class ImageChunk final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:imageconv.ImageChunk) */ {
 public:
  inline ImageChunk() : ImageChunk(nullptr) {}
  ~ImageChunk() override;
  explicit PROTOBUF_CONSTEXPR ImageChunk(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ImageChunk(const ImageChunk& from);
  ImageChunk(ImageChunk&& from) noexcept
    : ImageChunk() {
    *this = ::std::move(from);
  }

  inline ImageChunk& operator=(const ImageChunk& from) {
    CopyFrom(from);
    return *this;
  }
  inline ImageChunk& operator=(ImageChunk&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ImageChunk& default_instance() {
    return *internal_default_instance();
  }
  static inline const ImageChunk* internal_default_instance() {
    return reinterpret_cast<const ImageChunk*>(
               &_ImageChunk_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ImageChunk& a, ImageChunk& b) {
    a.Swap(&b);
  }
  inline void Swap(ImageChunk* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ImageChunk* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ImageChunk* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ImageChunk>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ImageChunk& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ImageChunk& from) {
    ImageChunk::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ImageChunk* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "imageconv.ImageChunk";
  }
  protected:
  explicit ImageChunk(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKernelFieldNumber = 8,
    kChunkDataFieldNumber = 1,
    kChunkIndexFieldNumber = 2,
    kTotalChunksFieldNumber = 3,
    kStartRowFieldNumber = 4,
    kNumRowsFieldNumber = 5,
    kImgWidthFieldNumber = 6,
    kImgHeightFieldNumber = 7,
    kHasHaloTopFieldNumber = 9,
    kHasHaloBottomFieldNumber = 10,
  };
  // repeated int32 kernel = 8;
  int kernel_size() const;
  private:
  int _internal_kernel_size() const;
  public:
  void clear_kernel();
  private:
  int32_t _internal_kernel(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_kernel() const;
  void _internal_add_kernel(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_kernel();
  public:
  int32_t kernel(int index) const;
  void set_kernel(int index, int32_t value);
  void add_kernel(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      kernel() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_kernel();

  // bytes chunk_data = 1;
  void clear_chunk_data();
  const std::string& chunk_data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_chunk_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_chunk_data();
  PROTOBUF_NODISCARD std::string* release_chunk_data();
  void set_allocated_chunk_data(std::string* chunk_data);
  private:
  const std::string& _internal_chunk_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_chunk_data(const std::string& value);
  std::string* _internal_mutable_chunk_data();
  public:

  // int32 chunk_index = 2;
  void clear_chunk_index();
  int32_t chunk_index() const;
  void set_chunk_index(int32_t value);
  private:
  int32_t _internal_chunk_index() const;
  void _internal_set_chunk_index(int32_t value);
  public:

  // int32 total_chunks = 3;
  void clear_total_chunks();
  int32_t total_chunks() const;
  void set_total_chunks(int32_t value);
  private:
  int32_t _internal_total_chunks() const;
  void _internal_set_total_chunks(int32_t value);
  public:

  // int32 start_row = 4;
  void clear_start_row();
  int32_t start_row() const;
  void set_start_row(int32_t value);
  private:
  int32_t _internal_start_row() const;
  void _internal_set_start_row(int32_t value);
  public:

  // int32 num_rows = 5;
  void clear_num_rows();
  int32_t num_rows() const;
  void set_num_rows(int32_t value);
  private:
  int32_t _internal_num_rows() const;
  void _internal_set_num_rows(int32_t value);
  public:

  // int32 img_width = 6;
  void clear_img_width();
  int32_t img_width() const;
  void set_img_width(int32_t value);
  private:
  int32_t _internal_img_width() const;
  void _internal_set_img_width(int32_t value);
  public:

  // int32 img_height = 7;
  void clear_img_height();
  int32_t img_height() const;
  void set_img_height(int32_t value);
  private:
  int32_t _internal_img_height() const;
  void _internal_set_img_height(int32_t value);
  public:

  // bool has_halo_top = 9;
  void clear_has_halo_top();
  bool has_halo_top() const;
  void set_has_halo_top(bool value);
  private:
  bool _internal_has_halo_top() const;
  void _internal_set_has_halo_top(bool value);
  public:

  // bool has_halo_bottom = 10;
  void clear_has_halo_bottom();
  bool has_halo_bottom() const;
  void set_has_halo_bottom(bool value);
  private:
  bool _internal_has_halo_bottom() const;
  void _internal_set_has_halo_bottom(bool value);
  public:

  // @@protoc_insertion_point(class_scope:imageconv.ImageChunk)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > kernel_;
    mutable std::atomic<int> _kernel_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr chunk_data_;
    int32_t chunk_index_;
    int32_t total_chunks_;
    int32_t start_row_;
    int32_t num_rows_;
    int32_t img_width_;
    int32_t img_height_;
    bool has_halo_top_;
    bool has_halo_bottom_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_imageConvolution_2eproto;
};
// -------------------------------------------------------------------

class ConvolutionResult final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:imageconv.ConvolutionResult) */ {
 public:
  inline ConvolutionResult() : ConvolutionResult(nullptr) {}
  ~ConvolutionResult() override;
  explicit PROTOBUF_CONSTEXPR ConvolutionResult(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ConvolutionResult(const ConvolutionResult& from);
  ConvolutionResult(ConvolutionResult&& from) noexcept
    : ConvolutionResult() {
    *this = ::std::move(from);
  }

  inline ConvolutionResult& operator=(const ConvolutionResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline ConvolutionResult& operator=(ConvolutionResult&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ConvolutionResult& default_instance() {
    return *internal_default_instance();
  }
  static inline const ConvolutionResult* internal_default_instance() {
    return reinterpret_cast<const ConvolutionResult*>(
               &_ConvolutionResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ConvolutionResult& a, ConvolutionResult& b) {
    a.Swap(&b);
  }
  inline void Swap(ConvolutionResult* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ConvolutionResult* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ConvolutionResult* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ConvolutionResult>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ConvolutionResult& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ConvolutionResult& from) {
    ConvolutionResult::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ConvolutionResult* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "imageconv.ConvolutionResult";
  }
  protected:
  explicit ConvolutionResult(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResultDataFieldNumber = 1,
    kErrorMessageFieldNumber = 4,
    kChunkIndexFieldNumber = 2,
    kSuccessFieldNumber = 3,
  };
  // bytes result_data = 1;
  void clear_result_data();
  const std::string& result_data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_result_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_result_data();
  PROTOBUF_NODISCARD std::string* release_result_data();
  void set_allocated_result_data(std::string* result_data);
  private:
  const std::string& _internal_result_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_result_data(const std::string& value);
  std::string* _internal_mutable_result_data();
  public:

  // string error_message = 4;
  void clear_error_message();
  const std::string& error_message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_error_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_error_message();
  PROTOBUF_NODISCARD std::string* release_error_message();
  void set_allocated_error_message(std::string* error_message);
  private:
  const std::string& _internal_error_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error_message(const std::string& value);
  std::string* _internal_mutable_error_message();
  public:

  // int32 chunk_index = 2;
  void clear_chunk_index();
  int32_t chunk_index() const;
  void set_chunk_index(int32_t value);
  private:
  int32_t _internal_chunk_index() const;
  void _internal_set_chunk_index(int32_t value);
  public:

  // bool success = 3;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:imageconv.ConvolutionResult)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr result_data_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_message_;
    int32_t chunk_index_;
    bool success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_imageConvolution_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ImageChunk

// bytes chunk_data = 1;
inline void ImageChunk::clear_chunk_data() {
  _impl_.chunk_data_.ClearToEmpty();
}
inline const std::string& ImageChunk::chunk_data() const {
  // @@protoc_insertion_point(field_get:imageconv.ImageChunk.chunk_data)
  return _internal_chunk_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ImageChunk::set_chunk_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.chunk_data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:imageconv.ImageChunk.chunk_data)
}
inline std::string* ImageChunk::mutable_chunk_data() {
  std::string* _s = _internal_mutable_chunk_data();
  // @@protoc_insertion_point(field_mutable:imageconv.ImageChunk.chunk_data)
  return _s;
}
inline const std::string& ImageChunk::_internal_chunk_data() const {
  return _impl_.chunk_data_.Get();
}
inline void ImageChunk::_internal_set_chunk_data(const std::string& value) {
  
  _impl_.chunk_data_.Set(value, GetArenaForAllocation());
}
inline std::string* ImageChunk::_internal_mutable_chunk_data() {
  
  return _impl_.chunk_data_.Mutable(GetArenaForAllocation());
}
inline std::string* ImageChunk::release_chunk_data() {
  // @@protoc_insertion_point(field_release:imageconv.ImageChunk.chunk_data)
  return _impl_.chunk_data_.Release();
}
inline void ImageChunk::set_allocated_chunk_data(std::string* chunk_data) {
  if (chunk_data != nullptr) {
    
  } else {
    
  }
  _impl_.chunk_data_.SetAllocated(chunk_data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.chunk_data_.IsDefault()) {
    _impl_.chunk_data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:imageconv.ImageChunk.chunk_data)
}

// int32 chunk_index = 2;
inline void ImageChunk::clear_chunk_index() {
  _impl_.chunk_index_ = 0;
}
inline int32_t ImageChunk::_internal_chunk_index() const {
  return _impl_.chunk_index_;
}
inline int32_t ImageChunk::chunk_index() const {
  // @@protoc_insertion_point(field_get:imageconv.ImageChunk.chunk_index)
  return _internal_chunk_index();
}
inline void ImageChunk::_internal_set_chunk_index(int32_t value) {
  
  _impl_.chunk_index_ = value;
}
inline void ImageChunk::set_chunk_index(int32_t value) {
  _internal_set_chunk_index(value);
  // @@protoc_insertion_point(field_set:imageconv.ImageChunk.chunk_index)
}

// int32 total_chunks = 3;
inline void ImageChunk::clear_total_chunks() {
  _impl_.total_chunks_ = 0;
}
inline int32_t ImageChunk::_internal_total_chunks() const {
  return _impl_.total_chunks_;
}
inline int32_t ImageChunk::total_chunks() const {
  // @@protoc_insertion_point(field_get:imageconv.ImageChunk.total_chunks)
  return _internal_total_chunks();
}
inline void ImageChunk::_internal_set_total_chunks(int32_t value) {
  
  _impl_.total_chunks_ = value;
}
inline void ImageChunk::set_total_chunks(int32_t value) {
  _internal_set_total_chunks(value);
  // @@protoc_insertion_point(field_set:imageconv.ImageChunk.total_chunks)
}

// int32 start_row = 4;
inline void ImageChunk::clear_start_row() {
  _impl_.start_row_ = 0;
}
inline int32_t ImageChunk::_internal_start_row() const {
  return _impl_.start_row_;
}
inline int32_t ImageChunk::start_row() const {
  // @@protoc_insertion_point(field_get:imageconv.ImageChunk.start_row)
  return _internal_start_row();
}
inline void ImageChunk::_internal_set_start_row(int32_t value) {
  
  _impl_.start_row_ = value;
}
inline void ImageChunk::set_start_row(int32_t value) {
  _internal_set_start_row(value);
  // @@protoc_insertion_point(field_set:imageconv.ImageChunk.start_row)
}

// int32 num_rows = 5;
inline void ImageChunk::clear_num_rows() {
  _impl_.num_rows_ = 0;
}
inline int32_t ImageChunk::_internal_num_rows() const {
  return _impl_.num_rows_;
}
inline int32_t ImageChunk::num_rows() const {
  // @@protoc_insertion_point(field_get:imageconv.ImageChunk.num_rows)
  return _internal_num_rows();
}
inline void ImageChunk::_internal_set_num_rows(int32_t value) {
  
  _impl_.num_rows_ = value;
}
inline void ImageChunk::set_num_rows(int32_t value) {
  _internal_set_num_rows(value);
  // @@protoc_insertion_point(field_set:imageconv.ImageChunk.num_rows)
}

// int32 img_width = 6;
inline void ImageChunk::clear_img_width() {
  _impl_.img_width_ = 0;
}
inline int32_t ImageChunk::_internal_img_width() const {
  return _impl_.img_width_;
}
inline int32_t ImageChunk::img_width() const {
  // @@protoc_insertion_point(field_get:imageconv.ImageChunk.img_width)
  return _internal_img_width();
}
inline void ImageChunk::_internal_set_img_width(int32_t value) {
  
  _impl_.img_width_ = value;
}
inline void ImageChunk::set_img_width(int32_t value) {
  _internal_set_img_width(value);
  // @@protoc_insertion_point(field_set:imageconv.ImageChunk.img_width)
}

// int32 img_height = 7;
inline void ImageChunk::clear_img_height() {
  _impl_.img_height_ = 0;
}
inline int32_t ImageChunk::_internal_img_height() const {
  return _impl_.img_height_;
}
inline int32_t ImageChunk::img_height() const {
  // @@protoc_insertion_point(field_get:imageconv.ImageChunk.img_height)
  return _internal_img_height();
}
inline void ImageChunk::_internal_set_img_height(int32_t value) {
  
  _impl_.img_height_ = value;
}
inline void ImageChunk::set_img_height(int32_t value) {
  _internal_set_img_height(value);
  // @@protoc_insertion_point(field_set:imageconv.ImageChunk.img_height)
}

// repeated int32 kernel = 8;
inline int ImageChunk::_internal_kernel_size() const {
  return _impl_.kernel_.size();
}
inline int ImageChunk::kernel_size() const {
  return _internal_kernel_size();
}
inline void ImageChunk::clear_kernel() {
  _impl_.kernel_.Clear();
}
inline int32_t ImageChunk::_internal_kernel(int index) const {
  return _impl_.kernel_.Get(index);
}
inline int32_t ImageChunk::kernel(int index) const {
  // @@protoc_insertion_point(field_get:imageconv.ImageChunk.kernel)
  return _internal_kernel(index);
}
inline void ImageChunk::set_kernel(int index, int32_t value) {
  _impl_.kernel_.Set(index, value);
  // @@protoc_insertion_point(field_set:imageconv.ImageChunk.kernel)
}
inline void ImageChunk::_internal_add_kernel(int32_t value) {
  _impl_.kernel_.Add(value);
}
inline void ImageChunk::add_kernel(int32_t value) {
  _internal_add_kernel(value);
  // @@protoc_insertion_point(field_add:imageconv.ImageChunk.kernel)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
ImageChunk::_internal_kernel() const {
  return _impl_.kernel_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
ImageChunk::kernel() const {
  // @@protoc_insertion_point(field_list:imageconv.ImageChunk.kernel)
  return _internal_kernel();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
ImageChunk::_internal_mutable_kernel() {
  return &_impl_.kernel_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
ImageChunk::mutable_kernel() {
  // @@protoc_insertion_point(field_mutable_list:imageconv.ImageChunk.kernel)
  return _internal_mutable_kernel();
}

// bool has_halo_top = 9;
inline void ImageChunk::clear_has_halo_top() {
  _impl_.has_halo_top_ = false;
}
inline bool ImageChunk::_internal_has_halo_top() const {
  return _impl_.has_halo_top_;
}
inline bool ImageChunk::has_halo_top() const {
  // @@protoc_insertion_point(field_get:imageconv.ImageChunk.has_halo_top)
  return _internal_has_halo_top();
}
inline void ImageChunk::_internal_set_has_halo_top(bool value) {
  
  _impl_.has_halo_top_ = value;
}
inline void ImageChunk::set_has_halo_top(bool value) {
  _internal_set_has_halo_top(value);
  // @@protoc_insertion_point(field_set:imageconv.ImageChunk.has_halo_top)
}

// bool has_halo_bottom = 10;
inline void ImageChunk::clear_has_halo_bottom() {
  _impl_.has_halo_bottom_ = false;
}
inline bool ImageChunk::_internal_has_halo_bottom() const {
  return _impl_.has_halo_bottom_;
}
inline bool ImageChunk::has_halo_bottom() const {
  // @@protoc_insertion_point(field_get:imageconv.ImageChunk.has_halo_bottom)
  return _internal_has_halo_bottom();
}
inline void ImageChunk::_internal_set_has_halo_bottom(bool value) {
  
  _impl_.has_halo_bottom_ = value;
}
inline void ImageChunk::set_has_halo_bottom(bool value) {
  _internal_set_has_halo_bottom(value);
  // @@protoc_insertion_point(field_set:imageconv.ImageChunk.has_halo_bottom)
}

// -------------------------------------------------------------------

// ConvolutionResult

// bytes result_data = 1;
inline void ConvolutionResult::clear_result_data() {
  _impl_.result_data_.ClearToEmpty();
}
inline const std::string& ConvolutionResult::result_data() const {
  // @@protoc_insertion_point(field_get:imageconv.ConvolutionResult.result_data)
  return _internal_result_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ConvolutionResult::set_result_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.result_data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:imageconv.ConvolutionResult.result_data)
}
inline std::string* ConvolutionResult::mutable_result_data() {
  std::string* _s = _internal_mutable_result_data();
  // @@protoc_insertion_point(field_mutable:imageconv.ConvolutionResult.result_data)
  return _s;
}
inline const std::string& ConvolutionResult::_internal_result_data() const {
  return _impl_.result_data_.Get();
}
inline void ConvolutionResult::_internal_set_result_data(const std::string& value) {
  
  _impl_.result_data_.Set(value, GetArenaForAllocation());
}
inline std::string* ConvolutionResult::_internal_mutable_result_data() {
  
  return _impl_.result_data_.Mutable(GetArenaForAllocation());
}
inline std::string* ConvolutionResult::release_result_data() {
  // @@protoc_insertion_point(field_release:imageconv.ConvolutionResult.result_data)
  return _impl_.result_data_.Release();
}
inline void ConvolutionResult::set_allocated_result_data(std::string* result_data) {
  if (result_data != nullptr) {
    
  } else {
    
  }
  _impl_.result_data_.SetAllocated(result_data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.result_data_.IsDefault()) {
    _impl_.result_data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:imageconv.ConvolutionResult.result_data)
}

// int32 chunk_index = 2;
inline void ConvolutionResult::clear_chunk_index() {
  _impl_.chunk_index_ = 0;
}
inline int32_t ConvolutionResult::_internal_chunk_index() const {
  return _impl_.chunk_index_;
}
inline int32_t ConvolutionResult::chunk_index() const {
  // @@protoc_insertion_point(field_get:imageconv.ConvolutionResult.chunk_index)
  return _internal_chunk_index();
}
inline void ConvolutionResult::_internal_set_chunk_index(int32_t value) {
  
  _impl_.chunk_index_ = value;
}
inline void ConvolutionResult::set_chunk_index(int32_t value) {
  _internal_set_chunk_index(value);
  // @@protoc_insertion_point(field_set:imageconv.ConvolutionResult.chunk_index)
}

// bool success = 3;
inline void ConvolutionResult::clear_success() {
  _impl_.success_ = false;
}
inline bool ConvolutionResult::_internal_success() const {
  return _impl_.success_;
}
inline bool ConvolutionResult::success() const {
  // @@protoc_insertion_point(field_get:imageconv.ConvolutionResult.success)
  return _internal_success();
}
inline void ConvolutionResult::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void ConvolutionResult::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:imageconv.ConvolutionResult.success)
}

// string error_message = 4;
inline void ConvolutionResult::clear_error_message() {
  _impl_.error_message_.ClearToEmpty();
}
inline const std::string& ConvolutionResult::error_message() const {
  // @@protoc_insertion_point(field_get:imageconv.ConvolutionResult.error_message)
  return _internal_error_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ConvolutionResult::set_error_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.error_message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:imageconv.ConvolutionResult.error_message)
}
inline std::string* ConvolutionResult::mutable_error_message() {
  std::string* _s = _internal_mutable_error_message();
  // @@protoc_insertion_point(field_mutable:imageconv.ConvolutionResult.error_message)
  return _s;
}
inline const std::string& ConvolutionResult::_internal_error_message() const {
  return _impl_.error_message_.Get();
}
inline void ConvolutionResult::_internal_set_error_message(const std::string& value) {
  
  _impl_.error_message_.Set(value, GetArenaForAllocation());
}
inline std::string* ConvolutionResult::_internal_mutable_error_message() {
  
  return _impl_.error_message_.Mutable(GetArenaForAllocation());
}
inline std::string* ConvolutionResult::release_error_message() {
  // @@protoc_insertion_point(field_release:imageconv.ConvolutionResult.error_message)
  return _impl_.error_message_.Release();
}
inline void ConvolutionResult::set_allocated_error_message(std::string* error_message) {
  if (error_message != nullptr) {
    
  } else {
    
  }
  _impl_.error_message_.SetAllocated(error_message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.error_message_.IsDefault()) {
    _impl_.error_message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:imageconv.ConvolutionResult.error_message)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace imageconv

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_imageConvolution_2eproto
