// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: imageConvolution.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_imageConvolution_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_imageConvolution_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_imageConvolution_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_imageConvolution_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_imageConvolution_2eproto;
namespace imageconv {
class ConvolutionResult;
class ConvolutionResultDefaultTypeInternal;
extern ConvolutionResultDefaultTypeInternal _ConvolutionResult_default_instance_;
class ImageChunk;
class ImageChunkDefaultTypeInternal;
extern ImageChunkDefaultTypeInternal _ImageChunk_default_instance_;
}  // namespace imageconv
PROTOBUF_NAMESPACE_OPEN
template<> ::imageconv::ConvolutionResult* Arena::CreateMaybeMessage<::imageconv::ConvolutionResult>(Arena*);
template<> ::imageconv::ImageChunk* Arena::CreateMaybeMessage<::imageconv::ImageChunk>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace imageconv {

// ===================================================================

class ImageChunk PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:imageconv.ImageChunk) */ {
 public:
  inline ImageChunk() : ImageChunk(nullptr) {};
  virtual ~ImageChunk();

  ImageChunk(const ImageChunk& from);
  ImageChunk(ImageChunk&& from) noexcept
    : ImageChunk() {
    *this = ::std::move(from);
  }

  inline ImageChunk& operator=(const ImageChunk& from) {
    CopyFrom(from);
    return *this;
  }
  inline ImageChunk& operator=(ImageChunk&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ImageChunk& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ImageChunk* internal_default_instance() {
    return reinterpret_cast<const ImageChunk*>(
               &_ImageChunk_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ImageChunk& a, ImageChunk& b) {
    a.Swap(&b);
  }
  inline void Swap(ImageChunk* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ImageChunk* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ImageChunk* New() const final {
    return CreateMaybeMessage<ImageChunk>(nullptr);
  }

  ImageChunk* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ImageChunk>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ImageChunk& from);
  void MergeFrom(const ImageChunk& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ImageChunk* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "imageconv.ImageChunk";
  }
  protected:
  explicit ImageChunk(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_imageConvolution_2eproto);
    return ::descriptor_table_imageConvolution_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKernelFieldNumber = 8,
    kChunkDataFieldNumber = 1,
    kChunkIndexFieldNumber = 2,
    kTotalChunksFieldNumber = 3,
    kStartRowFieldNumber = 4,
    kNumRowsFieldNumber = 5,
    kImgWidthFieldNumber = 6,
    kImgHeightFieldNumber = 7,
    kHasHaloTopFieldNumber = 9,
    kHasHaloBottomFieldNumber = 10,
  };
  // repeated int32 kernel = 8;
  int kernel_size() const;
  private:
  int _internal_kernel_size() const;
  public:
  void clear_kernel();
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_kernel(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      _internal_kernel() const;
  void _internal_add_kernel(::PROTOBUF_NAMESPACE_ID::int32 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      _internal_mutable_kernel();
  public:
  ::PROTOBUF_NAMESPACE_ID::int32 kernel(int index) const;
  void set_kernel(int index, ::PROTOBUF_NAMESPACE_ID::int32 value);
  void add_kernel(::PROTOBUF_NAMESPACE_ID::int32 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      kernel() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      mutable_kernel();

  // bytes chunk_data = 1;
  void clear_chunk_data();
  const std::string& chunk_data() const;
  void set_chunk_data(const std::string& value);
  void set_chunk_data(std::string&& value);
  void set_chunk_data(const char* value);
  void set_chunk_data(const void* value, size_t size);
  std::string* mutable_chunk_data();
  std::string* release_chunk_data();
  void set_allocated_chunk_data(std::string* chunk_data);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_chunk_data();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_chunk_data(
      std::string* chunk_data);
  private:
  const std::string& _internal_chunk_data() const;
  void _internal_set_chunk_data(const std::string& value);
  std::string* _internal_mutable_chunk_data();
  public:

  // int32 chunk_index = 2;
  void clear_chunk_index();
  ::PROTOBUF_NAMESPACE_ID::int32 chunk_index() const;
  void set_chunk_index(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_chunk_index() const;
  void _internal_set_chunk_index(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 total_chunks = 3;
  void clear_total_chunks();
  ::PROTOBUF_NAMESPACE_ID::int32 total_chunks() const;
  void set_total_chunks(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_total_chunks() const;
  void _internal_set_total_chunks(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 start_row = 4;
  void clear_start_row();
  ::PROTOBUF_NAMESPACE_ID::int32 start_row() const;
  void set_start_row(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_start_row() const;
  void _internal_set_start_row(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 num_rows = 5;
  void clear_num_rows();
  ::PROTOBUF_NAMESPACE_ID::int32 num_rows() const;
  void set_num_rows(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_num_rows() const;
  void _internal_set_num_rows(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 img_width = 6;
  void clear_img_width();
  ::PROTOBUF_NAMESPACE_ID::int32 img_width() const;
  void set_img_width(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_img_width() const;
  void _internal_set_img_width(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 img_height = 7;
  void clear_img_height();
  ::PROTOBUF_NAMESPACE_ID::int32 img_height() const;
  void set_img_height(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_img_height() const;
  void _internal_set_img_height(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // bool has_halo_top = 9;
  void clear_has_halo_top();
  bool has_halo_top() const;
  void set_has_halo_top(bool value);
  private:
  bool _internal_has_halo_top() const;
  void _internal_set_has_halo_top(bool value);
  public:

  // bool has_halo_bottom = 10;
  void clear_has_halo_bottom();
  bool has_halo_bottom() const;
  void set_has_halo_bottom(bool value);
  private:
  bool _internal_has_halo_bottom() const;
  void _internal_set_has_halo_bottom(bool value);
  public:

  // @@protoc_insertion_point(class_scope:imageconv.ImageChunk)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 > kernel_;
  mutable std::atomic<int> _kernel_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr chunk_data_;
  ::PROTOBUF_NAMESPACE_ID::int32 chunk_index_;
  ::PROTOBUF_NAMESPACE_ID::int32 total_chunks_;
  ::PROTOBUF_NAMESPACE_ID::int32 start_row_;
  ::PROTOBUF_NAMESPACE_ID::int32 num_rows_;
  ::PROTOBUF_NAMESPACE_ID::int32 img_width_;
  ::PROTOBUF_NAMESPACE_ID::int32 img_height_;
  bool has_halo_top_;
  bool has_halo_bottom_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_imageConvolution_2eproto;
};
// -------------------------------------------------------------------

class ConvolutionResult PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:imageconv.ConvolutionResult) */ {
 public:
  inline ConvolutionResult() : ConvolutionResult(nullptr) {};
  virtual ~ConvolutionResult();

  ConvolutionResult(const ConvolutionResult& from);
  ConvolutionResult(ConvolutionResult&& from) noexcept
    : ConvolutionResult() {
    *this = ::std::move(from);
  }

  inline ConvolutionResult& operator=(const ConvolutionResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline ConvolutionResult& operator=(ConvolutionResult&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ConvolutionResult& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ConvolutionResult* internal_default_instance() {
    return reinterpret_cast<const ConvolutionResult*>(
               &_ConvolutionResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ConvolutionResult& a, ConvolutionResult& b) {
    a.Swap(&b);
  }
  inline void Swap(ConvolutionResult* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ConvolutionResult* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ConvolutionResult* New() const final {
    return CreateMaybeMessage<ConvolutionResult>(nullptr);
  }

  ConvolutionResult* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ConvolutionResult>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ConvolutionResult& from);
  void MergeFrom(const ConvolutionResult& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ConvolutionResult* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "imageconv.ConvolutionResult";
  }
  protected:
  explicit ConvolutionResult(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_imageConvolution_2eproto);
    return ::descriptor_table_imageConvolution_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResultDataFieldNumber = 1,
    kErrorMessageFieldNumber = 4,
    kChunkIndexFieldNumber = 2,
    kSuccessFieldNumber = 3,
  };
  // bytes result_data = 1;
  void clear_result_data();
  const std::string& result_data() const;
  void set_result_data(const std::string& value);
  void set_result_data(std::string&& value);
  void set_result_data(const char* value);
  void set_result_data(const void* value, size_t size);
  std::string* mutable_result_data();
  std::string* release_result_data();
  void set_allocated_result_data(std::string* result_data);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_result_data();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_result_data(
      std::string* result_data);
  private:
  const std::string& _internal_result_data() const;
  void _internal_set_result_data(const std::string& value);
  std::string* _internal_mutable_result_data();
  public:

  // string error_message = 4;
  void clear_error_message();
  const std::string& error_message() const;
  void set_error_message(const std::string& value);
  void set_error_message(std::string&& value);
  void set_error_message(const char* value);
  void set_error_message(const char* value, size_t size);
  std::string* mutable_error_message();
  std::string* release_error_message();
  void set_allocated_error_message(std::string* error_message);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_error_message();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_error_message(
      std::string* error_message);
  private:
  const std::string& _internal_error_message() const;
  void _internal_set_error_message(const std::string& value);
  std::string* _internal_mutable_error_message();
  public:

  // int32 chunk_index = 2;
  void clear_chunk_index();
  ::PROTOBUF_NAMESPACE_ID::int32 chunk_index() const;
  void set_chunk_index(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_chunk_index() const;
  void _internal_set_chunk_index(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // bool success = 3;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:imageconv.ConvolutionResult)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr result_data_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_message_;
  ::PROTOBUF_NAMESPACE_ID::int32 chunk_index_;
  bool success_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_imageConvolution_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ImageChunk

// bytes chunk_data = 1;
inline void ImageChunk::clear_chunk_data() {
  chunk_data_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ImageChunk::chunk_data() const {
  // @@protoc_insertion_point(field_get:imageconv.ImageChunk.chunk_data)
  return _internal_chunk_data();
}
inline void ImageChunk::set_chunk_data(const std::string& value) {
  _internal_set_chunk_data(value);
  // @@protoc_insertion_point(field_set:imageconv.ImageChunk.chunk_data)
}
inline std::string* ImageChunk::mutable_chunk_data() {
  // @@protoc_insertion_point(field_mutable:imageconv.ImageChunk.chunk_data)
  return _internal_mutable_chunk_data();
}
inline const std::string& ImageChunk::_internal_chunk_data() const {
  return chunk_data_.Get();
}
inline void ImageChunk::_internal_set_chunk_data(const std::string& value) {
  
  chunk_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ImageChunk::set_chunk_data(std::string&& value) {
  
  chunk_data_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:imageconv.ImageChunk.chunk_data)
}
inline void ImageChunk::set_chunk_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  chunk_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:imageconv.ImageChunk.chunk_data)
}
inline void ImageChunk::set_chunk_data(const void* value,
    size_t size) {
  
  chunk_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:imageconv.ImageChunk.chunk_data)
}
inline std::string* ImageChunk::_internal_mutable_chunk_data() {
  
  return chunk_data_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ImageChunk::release_chunk_data() {
  // @@protoc_insertion_point(field_release:imageconv.ImageChunk.chunk_data)
  return chunk_data_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ImageChunk::set_allocated_chunk_data(std::string* chunk_data) {
  if (chunk_data != nullptr) {
    
  } else {
    
  }
  chunk_data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), chunk_data,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:imageconv.ImageChunk.chunk_data)
}
inline std::string* ImageChunk::unsafe_arena_release_chunk_data() {
  // @@protoc_insertion_point(field_unsafe_arena_release:imageconv.ImageChunk.chunk_data)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return chunk_data_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void ImageChunk::unsafe_arena_set_allocated_chunk_data(
    std::string* chunk_data) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (chunk_data != nullptr) {
    
  } else {
    
  }
  chunk_data_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      chunk_data, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:imageconv.ImageChunk.chunk_data)
}

// int32 chunk_index = 2;
inline void ImageChunk::clear_chunk_index() {
  chunk_index_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ImageChunk::_internal_chunk_index() const {
  return chunk_index_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ImageChunk::chunk_index() const {
  // @@protoc_insertion_point(field_get:imageconv.ImageChunk.chunk_index)
  return _internal_chunk_index();
}
inline void ImageChunk::_internal_set_chunk_index(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  chunk_index_ = value;
}
inline void ImageChunk::set_chunk_index(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_chunk_index(value);
  // @@protoc_insertion_point(field_set:imageconv.ImageChunk.chunk_index)
}

// int32 total_chunks = 3;
inline void ImageChunk::clear_total_chunks() {
  total_chunks_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ImageChunk::_internal_total_chunks() const {
  return total_chunks_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ImageChunk::total_chunks() const {
  // @@protoc_insertion_point(field_get:imageconv.ImageChunk.total_chunks)
  return _internal_total_chunks();
}
inline void ImageChunk::_internal_set_total_chunks(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  total_chunks_ = value;
}
inline void ImageChunk::set_total_chunks(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_total_chunks(value);
  // @@protoc_insertion_point(field_set:imageconv.ImageChunk.total_chunks)
}

// int32 start_row = 4;
inline void ImageChunk::clear_start_row() {
  start_row_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ImageChunk::_internal_start_row() const {
  return start_row_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ImageChunk::start_row() const {
  // @@protoc_insertion_point(field_get:imageconv.ImageChunk.start_row)
  return _internal_start_row();
}
inline void ImageChunk::_internal_set_start_row(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  start_row_ = value;
}
inline void ImageChunk::set_start_row(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_start_row(value);
  // @@protoc_insertion_point(field_set:imageconv.ImageChunk.start_row)
}

// int32 num_rows = 5;
inline void ImageChunk::clear_num_rows() {
  num_rows_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ImageChunk::_internal_num_rows() const {
  return num_rows_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ImageChunk::num_rows() const {
  // @@protoc_insertion_point(field_get:imageconv.ImageChunk.num_rows)
  return _internal_num_rows();
}
inline void ImageChunk::_internal_set_num_rows(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  num_rows_ = value;
}
inline void ImageChunk::set_num_rows(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_num_rows(value);
  // @@protoc_insertion_point(field_set:imageconv.ImageChunk.num_rows)
}

// int32 img_width = 6;
inline void ImageChunk::clear_img_width() {
  img_width_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ImageChunk::_internal_img_width() const {
  return img_width_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ImageChunk::img_width() const {
  // @@protoc_insertion_point(field_get:imageconv.ImageChunk.img_width)
  return _internal_img_width();
}
inline void ImageChunk::_internal_set_img_width(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  img_width_ = value;
}
inline void ImageChunk::set_img_width(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_img_width(value);
  // @@protoc_insertion_point(field_set:imageconv.ImageChunk.img_width)
}

// int32 img_height = 7;
inline void ImageChunk::clear_img_height() {
  img_height_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ImageChunk::_internal_img_height() const {
  return img_height_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ImageChunk::img_height() const {
  // @@protoc_insertion_point(field_get:imageconv.ImageChunk.img_height)
  return _internal_img_height();
}
inline void ImageChunk::_internal_set_img_height(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  img_height_ = value;
}
inline void ImageChunk::set_img_height(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_img_height(value);
  // @@protoc_insertion_point(field_set:imageconv.ImageChunk.img_height)
}

// repeated int32 kernel = 8;
inline int ImageChunk::_internal_kernel_size() const {
  return kernel_.size();
}
inline int ImageChunk::kernel_size() const {
  return _internal_kernel_size();
}
inline void ImageChunk::clear_kernel() {
  kernel_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ImageChunk::_internal_kernel(int index) const {
  return kernel_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ImageChunk::kernel(int index) const {
  // @@protoc_insertion_point(field_get:imageconv.ImageChunk.kernel)
  return _internal_kernel(index);
}
inline void ImageChunk::set_kernel(int index, ::PROTOBUF_NAMESPACE_ID::int32 value) {
  kernel_.Set(index, value);
  // @@protoc_insertion_point(field_set:imageconv.ImageChunk.kernel)
}
inline void ImageChunk::_internal_add_kernel(::PROTOBUF_NAMESPACE_ID::int32 value) {
  kernel_.Add(value);
}
inline void ImageChunk::add_kernel(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_add_kernel(value);
  // @@protoc_insertion_point(field_add:imageconv.ImageChunk.kernel)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
ImageChunk::_internal_kernel() const {
  return kernel_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
ImageChunk::kernel() const {
  // @@protoc_insertion_point(field_list:imageconv.ImageChunk.kernel)
  return _internal_kernel();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
ImageChunk::_internal_mutable_kernel() {
  return &kernel_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
ImageChunk::mutable_kernel() {
  // @@protoc_insertion_point(field_mutable_list:imageconv.ImageChunk.kernel)
  return _internal_mutable_kernel();
}

// bool has_halo_top = 9;
inline void ImageChunk::clear_has_halo_top() {
  has_halo_top_ = false;
}
inline bool ImageChunk::_internal_has_halo_top() const {
  return has_halo_top_;
}
inline bool ImageChunk::has_halo_top() const {
  // @@protoc_insertion_point(field_get:imageconv.ImageChunk.has_halo_top)
  return _internal_has_halo_top();
}
inline void ImageChunk::_internal_set_has_halo_top(bool value) {
  
  has_halo_top_ = value;
}
inline void ImageChunk::set_has_halo_top(bool value) {
  _internal_set_has_halo_top(value);
  // @@protoc_insertion_point(field_set:imageconv.ImageChunk.has_halo_top)
}

// bool has_halo_bottom = 10;
inline void ImageChunk::clear_has_halo_bottom() {
  has_halo_bottom_ = false;
}
inline bool ImageChunk::_internal_has_halo_bottom() const {
  return has_halo_bottom_;
}
inline bool ImageChunk::has_halo_bottom() const {
  // @@protoc_insertion_point(field_get:imageconv.ImageChunk.has_halo_bottom)
  return _internal_has_halo_bottom();
}
inline void ImageChunk::_internal_set_has_halo_bottom(bool value) {
  
  has_halo_bottom_ = value;
}
inline void ImageChunk::set_has_halo_bottom(bool value) {
  _internal_set_has_halo_bottom(value);
  // @@protoc_insertion_point(field_set:imageconv.ImageChunk.has_halo_bottom)
}

// -------------------------------------------------------------------

// ConvolutionResult

// bytes result_data = 1;
inline void ConvolutionResult::clear_result_data() {
  result_data_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ConvolutionResult::result_data() const {
  // @@protoc_insertion_point(field_get:imageconv.ConvolutionResult.result_data)
  return _internal_result_data();
}
inline void ConvolutionResult::set_result_data(const std::string& value) {
  _internal_set_result_data(value);
  // @@protoc_insertion_point(field_set:imageconv.ConvolutionResult.result_data)
}
inline std::string* ConvolutionResult::mutable_result_data() {
  // @@protoc_insertion_point(field_mutable:imageconv.ConvolutionResult.result_data)
  return _internal_mutable_result_data();
}
inline const std::string& ConvolutionResult::_internal_result_data() const {
  return result_data_.Get();
}
inline void ConvolutionResult::_internal_set_result_data(const std::string& value) {
  
  result_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ConvolutionResult::set_result_data(std::string&& value) {
  
  result_data_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:imageconv.ConvolutionResult.result_data)
}
inline void ConvolutionResult::set_result_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  result_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:imageconv.ConvolutionResult.result_data)
}
inline void ConvolutionResult::set_result_data(const void* value,
    size_t size) {
  
  result_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:imageconv.ConvolutionResult.result_data)
}
inline std::string* ConvolutionResult::_internal_mutable_result_data() {
  
  return result_data_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ConvolutionResult::release_result_data() {
  // @@protoc_insertion_point(field_release:imageconv.ConvolutionResult.result_data)
  return result_data_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ConvolutionResult::set_allocated_result_data(std::string* result_data) {
  if (result_data != nullptr) {
    
  } else {
    
  }
  result_data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), result_data,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:imageconv.ConvolutionResult.result_data)
}
inline std::string* ConvolutionResult::unsafe_arena_release_result_data() {
  // @@protoc_insertion_point(field_unsafe_arena_release:imageconv.ConvolutionResult.result_data)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return result_data_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void ConvolutionResult::unsafe_arena_set_allocated_result_data(
    std::string* result_data) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (result_data != nullptr) {
    
  } else {
    
  }
  result_data_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      result_data, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:imageconv.ConvolutionResult.result_data)
}

// int32 chunk_index = 2;
inline void ConvolutionResult::clear_chunk_index() {
  chunk_index_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ConvolutionResult::_internal_chunk_index() const {
  return chunk_index_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ConvolutionResult::chunk_index() const {
  // @@protoc_insertion_point(field_get:imageconv.ConvolutionResult.chunk_index)
  return _internal_chunk_index();
}
inline void ConvolutionResult::_internal_set_chunk_index(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  chunk_index_ = value;
}
inline void ConvolutionResult::set_chunk_index(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_chunk_index(value);
  // @@protoc_insertion_point(field_set:imageconv.ConvolutionResult.chunk_index)
}

// bool success = 3;
inline void ConvolutionResult::clear_success() {
  success_ = false;
}
inline bool ConvolutionResult::_internal_success() const {
  return success_;
}
inline bool ConvolutionResult::success() const {
  // @@protoc_insertion_point(field_get:imageconv.ConvolutionResult.success)
  return _internal_success();
}
inline void ConvolutionResult::_internal_set_success(bool value) {
  
  success_ = value;
}
inline void ConvolutionResult::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:imageconv.ConvolutionResult.success)
}

// string error_message = 4;
inline void ConvolutionResult::clear_error_message() {
  error_message_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ConvolutionResult::error_message() const {
  // @@protoc_insertion_point(field_get:imageconv.ConvolutionResult.error_message)
  return _internal_error_message();
}
inline void ConvolutionResult::set_error_message(const std::string& value) {
  _internal_set_error_message(value);
  // @@protoc_insertion_point(field_set:imageconv.ConvolutionResult.error_message)
}
inline std::string* ConvolutionResult::mutable_error_message() {
  // @@protoc_insertion_point(field_mutable:imageconv.ConvolutionResult.error_message)
  return _internal_mutable_error_message();
}
inline const std::string& ConvolutionResult::_internal_error_message() const {
  return error_message_.Get();
}
inline void ConvolutionResult::_internal_set_error_message(const std::string& value) {
  
  error_message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ConvolutionResult::set_error_message(std::string&& value) {
  
  error_message_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:imageconv.ConvolutionResult.error_message)
}
inline void ConvolutionResult::set_error_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  error_message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:imageconv.ConvolutionResult.error_message)
}
inline void ConvolutionResult::set_error_message(const char* value,
    size_t size) {
  
  error_message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:imageconv.ConvolutionResult.error_message)
}
inline std::string* ConvolutionResult::_internal_mutable_error_message() {
  
  return error_message_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ConvolutionResult::release_error_message() {
  // @@protoc_insertion_point(field_release:imageconv.ConvolutionResult.error_message)
  return error_message_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ConvolutionResult::set_allocated_error_message(std::string* error_message) {
  if (error_message != nullptr) {
    
  } else {
    
  }
  error_message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), error_message,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:imageconv.ConvolutionResult.error_message)
}
inline std::string* ConvolutionResult::unsafe_arena_release_error_message() {
  // @@protoc_insertion_point(field_unsafe_arena_release:imageconv.ConvolutionResult.error_message)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return error_message_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void ConvolutionResult::unsafe_arena_set_allocated_error_message(
    std::string* error_message) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (error_message != nullptr) {
    
  } else {
    
  }
  error_message_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      error_message, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:imageconv.ConvolutionResult.error_message)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace imageconv

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_imageConvolution_2eproto
