// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: imageConvolution.proto
#ifndef GRPC_imageConvolution_2eproto__INCLUDED
#define GRPC_imageConvolution_2eproto__INCLUDED

#include "imageConvolution.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace imageconv {

class ImageConvolution final {
 public:
  static constexpr char const* service_full_name() {
    return "imageconv.ImageConvolution";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>> StreamConvolution(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>>(StreamConvolutionRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>> AsyncStreamConvolution(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>>(AsyncStreamConvolutionRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>> PrepareAsyncStreamConvolution(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>>(PrepareAsyncStreamConvolutionRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void StreamConvolution(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::imageconv::ImageChunk,::imageconv::ConvolutionResult>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderWriterInterface< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>* StreamConvolutionRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>* AsyncStreamConvolutionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>* PrepareAsyncStreamConvolutionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>> StreamConvolution(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>>(StreamConvolutionRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>> AsyncStreamConvolution(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>>(AsyncStreamConvolutionRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>> PrepareAsyncStreamConvolution(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>>(PrepareAsyncStreamConvolutionRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void StreamConvolution(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::imageconv::ImageChunk,::imageconv::ConvolutionResult>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReaderWriter< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>* StreamConvolutionRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>* AsyncStreamConvolutionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>* PrepareAsyncStreamConvolutionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_StreamConvolution_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status StreamConvolution(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::imageconv::ConvolutionResult, ::imageconv::ImageChunk>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamConvolution : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamConvolution() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_StreamConvolution() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamConvolution(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::imageconv::ConvolutionResult, ::imageconv::ImageChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamConvolution(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::imageconv::ConvolutionResult, ::imageconv::ImageChunk>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_StreamConvolution<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_StreamConvolution : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamConvolution() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->StreamConvolution(context); }));
    }
    ~WithCallbackMethod_StreamConvolution() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamConvolution(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::imageconv::ConvolutionResult, ::imageconv::ImageChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>* StreamConvolution(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_StreamConvolution<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_StreamConvolution : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamConvolution() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_StreamConvolution() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamConvolution(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::imageconv::ConvolutionResult, ::imageconv::ImageChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamConvolution : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamConvolution() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_StreamConvolution() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamConvolution(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::imageconv::ConvolutionResult, ::imageconv::ImageChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamConvolution(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamConvolution : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamConvolution() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->StreamConvolution(context); }));
    }
    ~WithRawCallbackMethod_StreamConvolution() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamConvolution(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::imageconv::ConvolutionResult, ::imageconv::ImageChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* StreamConvolution(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace imageconv


#endif  // GRPC_imageConvolution_2eproto__INCLUDED
