// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: imageConvolution.proto
#ifndef GRPC_imageConvolution_2eproto__INCLUDED
#define GRPC_imageConvolution_2eproto__INCLUDED

#include "imageConvolution.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace imageconv {

class ImageConvolution final {
 public:
  static constexpr char const* service_full_name() {
    return "imageconv.ImageConvolution";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>> StreamConvolution(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>>(StreamConvolutionRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>> AsyncStreamConvolution(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>>(AsyncStreamConvolutionRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>> PrepareAsyncStreamConvolution(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>>(PrepareAsyncStreamConvolutionRaw(context, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void StreamConvolution(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::imageconv::ImageChunk,::imageconv::ConvolutionResult>* reactor) = 0;
      #else
      virtual void StreamConvolution(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::imageconv::ImageChunk,::imageconv::ConvolutionResult>* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientReaderWriterInterface< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>* StreamConvolutionRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>* AsyncStreamConvolutionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>* PrepareAsyncStreamConvolutionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReaderWriter< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>> StreamConvolution(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>>(StreamConvolutionRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>> AsyncStreamConvolution(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>>(AsyncStreamConvolutionRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>> PrepareAsyncStreamConvolution(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>>(PrepareAsyncStreamConvolutionRaw(context, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void StreamConvolution(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::imageconv::ImageChunk,::imageconv::ConvolutionResult>* reactor) override;
      #else
      void StreamConvolution(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::imageconv::ImageChunk,::imageconv::ConvolutionResult>* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientReaderWriter< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>* StreamConvolutionRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>* AsyncStreamConvolutionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>* PrepareAsyncStreamConvolutionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_StreamConvolution_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status StreamConvolution(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::imageconv::ConvolutionResult, ::imageconv::ImageChunk>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamConvolution : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamConvolution() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_StreamConvolution() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamConvolution(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::imageconv::ConvolutionResult, ::imageconv::ImageChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamConvolution(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::imageconv::ConvolutionResult, ::imageconv::ImageChunk>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_StreamConvolution<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_StreamConvolution : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_StreamConvolution() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackBidiHandler< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context) { return this->StreamConvolution(context); }));
    }
    ~ExperimentalWithCallbackMethod_StreamConvolution() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamConvolution(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::imageconv::ConvolutionResult, ::imageconv::ImageChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerBidiReactor< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>* StreamConvolution(
      ::grpc::CallbackServerContext* /*context*/)
    #else
    virtual ::grpc::experimental::ServerBidiReactor< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>* StreamConvolution(
      ::grpc::experimental::CallbackServerContext* /*context*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_StreamConvolution<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_StreamConvolution<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_StreamConvolution : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamConvolution() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_StreamConvolution() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamConvolution(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::imageconv::ConvolutionResult, ::imageconv::ImageChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamConvolution : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamConvolution() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_StreamConvolution() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamConvolution(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::imageconv::ConvolutionResult, ::imageconv::ImageChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamConvolution(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_StreamConvolution : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_StreamConvolution() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context) { return this->StreamConvolution(context); }));
    }
    ~ExperimentalWithRawCallbackMethod_StreamConvolution() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamConvolution(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::imageconv::ConvolutionResult, ::imageconv::ImageChunk>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* StreamConvolution(
      ::grpc::CallbackServerContext* /*context*/)
    #else
    virtual ::grpc::experimental::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* StreamConvolution(
      ::grpc::experimental::CallbackServerContext* /*context*/)
    #endif
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace imageconv


#endif  // GRPC_imageConvolution_2eproto__INCLUDED
