// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: imageConvolution.proto

#include "imageConvolution.pb.h"
#include "imageConvolution.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace imageconv {

static const char* ImageConvolution_method_names[] = {
  "/imageconv.ImageConvolution/StreamConvolution",
};

std::unique_ptr< ImageConvolution::Stub> ImageConvolution::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ImageConvolution::Stub> stub(new ImageConvolution::Stub(channel, options));
  return stub;
}

ImageConvolution::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_StreamConvolution_(ImageConvolution_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>* ImageConvolution::Stub::StreamConvolutionRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>::Create(channel_.get(), rpcmethod_StreamConvolution_, context);
}

void ImageConvolution::Stub::async::StreamConvolution(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::imageconv::ImageChunk,::imageconv::ConvolutionResult>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::imageconv::ImageChunk,::imageconv::ConvolutionResult>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamConvolution_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>* ImageConvolution::Stub::AsyncStreamConvolutionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>::Create(channel_.get(), cq, rpcmethod_StreamConvolution_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>* ImageConvolution::Stub::PrepareAsyncStreamConvolutionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>::Create(channel_.get(), cq, rpcmethod_StreamConvolution_, context, false, nullptr);
}

ImageConvolution::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ImageConvolution_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< ImageConvolution::Service, ::imageconv::ImageChunk, ::imageconv::ConvolutionResult>(
          [](ImageConvolution::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::imageconv::ConvolutionResult,
             ::imageconv::ImageChunk>* stream) {
               return service->StreamConvolution(ctx, stream);
             }, this)));
}

ImageConvolution::Service::~Service() {
}

::grpc::Status ImageConvolution::Service::StreamConvolution(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::imageconv::ConvolutionResult, ::imageconv::ImageChunk>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace imageconv

